# Generated by Django 4.2.8 on 2024-05-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photored', '0003_post_delete_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('Graphics', 'Graphics'), ('3D', '3D'), ('2D', '2D'), ('Videos', 'Videos')], default='Graphics', max_length=20),
        ),
    ]
